# Generated by Django 2.0.2 on 2018-03-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DoB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='DoB',
            field=models.DateField(),
        ),
    ]
