# Generated by Django 2.0.2 on 2018-04-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='student',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
