# Generated by Django 2.0.2 on 2018-04-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180426_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='studentFeedback',
        ),
    ]
