# Generated by Django 2.0.2 on 2018-05-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_teacher_studentfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=75)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('contract', models.FileField(default='', upload_to='')),
                ('resume', models.FileField(default='', upload_to='')),
            ],
        ),
    ]
