# Generated by Django 2.0.2 on 2018-05-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180511_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='startDate',
        ),
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
