# Generated by Django 2.0.2 on 2018-05-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180517_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='home.Student'),
        ),
    ]
