# Generated by Django 2.0.2 on 2018-05-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180517_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(to='home.Student'),
        ),
    ]
