# Generated by Django 2.0.5 on 2018-05-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180522_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(blank=True, choices=[('PIANO', 'Piano lesson'), ('DRUM', 'Drum lesson'), ('GUITAR', 'Guitar lesson')], max_length=50, null=True),
        ),
    ]
