# Generated by Django 2.0.5 on 2018-05-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='room',
            field=models.CharField(blank=True, choices=[('Room 101', 'Room 101'), ('Room 102', 'Room 102'), ('Room 103', 'Room 103')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(blank=True, choices=[('Piano lesson', 'Piano lesson'), ('Drum lesson', 'Drum lesson'), ('Guitar lesson', 'Guitar lesson')], max_length=50, null=True),
        ),
    ]
