# Generated by Django 2.0.2 on 2018-04-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='studentFeedback',
            field=models.TextField(null=True),
        ),
    ]
