# Generated by Django 2.0.2 on 2018-05-11 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180511_2236'),
        ('student', '0003_auto_20180429_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire', models.CharField(choices=[('Buy', 'Buy'), ('Hire', 'Hire')], max_length=4)),
                ('approval', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending')], default='P', max_length=8)),
            ],
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='type',
            new_name='instrument_name',
        ),
        migrations.AddField(
            model_name='instrumentrequest',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Instrument'),
        ),
        migrations.AddField(
            model_name='instrumentrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
    ]
