# Generated by Django 2.0.2 on 2018-05-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180511_2236'),
        ('student', '0005_auto_20180511_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending')], default='P', max_length=8)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='instrumentrequest',
            name='approval',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending')], default='P', max_length=8),
        ),
        migrations.AlterField(
            model_name='instrumentrequest',
            name='hire',
            field=models.CharField(choices=[('Hire', 'Hire'), ('Buy', 'Buy')], max_length=4),
        ),
    ]
