# Generated by Django 2.0.2 on 2018-05-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20180517_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='student',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='user',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentrequest',
            name='hire',
            field=models.CharField(choices=[('Hire', 'Hire'), ('Buy', 'Buy')], max_length=4),
        ),
    ]
