# Generated by Django 2.0.2 on 2018-05-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20180517_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='prefLang',
            field=models.CharField(default='English', max_length=40),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='approval',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending')], default='P', max_length=8),
        ),
        migrations.AlterField(
            model_name='instrumentrequest',
            name='approval',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending')], default='P', max_length=8),
        ),
    ]
