# Generated by Django 2.0.2 on 2018-05-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20180518_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='approval',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending')], default='P', max_length=8),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
        migrations.AlterField(
            model_name='instrumentrequest',
            name='approval',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending')], default='P', max_length=8),
        ),
        migrations.AlterField(
            model_name='instrumentrequest',
            name='hire',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Hire', 'Hire')], max_length=4),
        ),
    ]
